# Generated by Django 5.1.3 on 2024-11-09 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_is_available_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartproduct',
            old_name='sub_total',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='cartproduct',
            old_name='total',
            new_name='subtotal',
        ),
    ]
