# Generated by Django 5.1.3 on 2024-11-10 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_cartproduct_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='sub_total',
            new_name='subtotal',
        ),
    ]
